spring:
  datasource:
    password: root
    username: root
    url: jdbc:mariadb://localhost:3306/sportFriend
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  jwt:
    secret-key: your-very-secret-key-that-is-at-least-32-characters-long
    expire-length: 3600000
